name: Setup Node.js with pnpm
description: Sets up Node.js and installs dependencies

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v1
      with:
        node-version: 'latest'
    - name: Install pnpm
      run: npm install -g pnpm
      shell: bash
    - name: Install dependencies
      run: pnpm install
      shell: bash
