name: Lint the codebase

permissions:
  contents: write

on:
  push:
    tags: []  # This ensures the workflow doesn't trigger for tags

jobs:
  lint:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/tags/*'  # Skip if it's a tag push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js with pnpm
        run: |
          npm install -g pnpm
          pnpm install  

      - name: Format frontend
        run: |
           cd apps/frontend
           pnpm prettier
      - name: Format backend
        run: |
           cd apps/backend
           pnpm prettier
      - name: Push changes
        run: |
           git config --global user.name "github-actions[bot]"
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
           git commit -am "chore: format codebase" || echo "No changes to commit"
           git diff --quiet || git push
           git push
        env:
          TOKEN: ${{ secrets.TOKEN }}
