name: On release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Extract version from tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Set version in package.json files
        run: |
          jq --arg version "$VERSION" '.version = $version' apps/backend/package.json > tmp.json && mv tmp.json apps/backend/package.json
          jq --arg version "$VERSION" '.version = $version' apps/frontend/package.json > tmp.json && mv tmp.json apps/frontend/package.json

      - name: Commit updated package.json files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "chore: set version to $VERSION"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git main

      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js with pnpm
        run: |
          npm install -g pnpm
          pnpm install  

      - name: Build frontend (Svelte)
        run: |
          cd apps/frontend
          pnpm build

      - name: Build backend (Electron)
        run: |
          cd apps/backend
          pnpm build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-build
          path: apps/backend/dist/

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: root/release_notes/${{ github.ref_name }}.md
          draft: ${{ endsWith(github.ref, 'rc') || endsWith(github.ref, 'dev') }}
          prerelease: ${{ endsWith(github.ref, 'rc') || endsWith(github.ref, 'dev') }}
          

