name: On release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      # - name: Extract version from tag
      #   run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      # - name: Set version in package.json files
      #   run: |
      #     echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      #     jq --arg version "$VERSION" '.version = $version' apps/backend/package.json | Set-Content -Path apps/backend/package.json
      #     jq --arg version "$VERSION" '.version = $version' apps/frontend/package.json | Set-Content -Path apps/frontend/package.json

      # - name: Commit updated package.json files
      #   run: |
      #     git config --global user.name "github-actions[bot]"
      #     git config --global user.email "github-actions[bot]@users.noreply.github.com"
      #     git commit -am "chore: set version to $VERSION"
      #     git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git main

      - name: Setup Node.js with pnpm
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
      - run: |
          npm install -g pnpm
          pnpm install

      - name: Build frontend (Svelte)
        run: |
          cd apps/frontend
          pnpm build

      - name: Build backend (Electron)
        run: |
          cd apps/backend
          pnpm build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-build
          path: apps/backend/dist/

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      